# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-20 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='do_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pu_date',
            field=models.DateField(null=True),
        ),
    ]
