# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-20 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20190120_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='do_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pu_time',
            field=models.TimeField(null=True),
        ),
    ]
